// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS2_RJCvaEyV3elNTkjnCf75BA-KAf-q0',
    appId: '1:604885963745:web:09f779c3a11adf7390f8a0',
    messagingSenderId: '604885963745',
    projectId: 'dtnd-2c0d6',
    authDomain: 'dtnd-2c0d6.firebaseapp.com',
    storageBucket: 'dtnd-2c0d6.appspot.com',
    measurementId: 'G-Z9KJJ9HB7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbFjpdKsuDi5A-umJw-qVsQX9DVrDeiQo',
    appId: '1:604885963745:android:9ddaea8e2034ae8d90f8a0',
    messagingSenderId: '604885963745',
    projectId: 'dtnd-2c0d6',
    storageBucket: 'dtnd-2c0d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7122mgP81IE6NJRz55W34S3--cxqHJqQ',
    appId: '1:604885963745:ios:9b9a5ad680b7f44290f8a0',
    messagingSenderId: '604885963745',
    projectId: 'dtnd-2c0d6',
    storageBucket: 'dtnd-2c0d6.appspot.com',
    androidClientId: '604885963745-lj0t1bk6r8gjmutq343eocmlv7h2nh0u.apps.googleusercontent.com',
    iosClientId: '604885963745-tpscahdfg48h3ppjqj4c762486lf91f0.apps.googleusercontent.com',
    iosBundleId: 'com.test.dtnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7122mgP81IE6NJRz55W34S3--cxqHJqQ',
    appId: '1:604885963745:ios:72f608511a5c36e690f8a0',
    messagingSenderId: '604885963745',
    projectId: 'dtnd-2c0d6',
    storageBucket: 'dtnd-2c0d6.appspot.com',
    androidClientId: '604885963745-lj0t1bk6r8gjmutq343eocmlv7h2nh0u.apps.googleusercontent.com',
    iosClientId: '604885963745-dq5g6c40ebf3723jo8gui8i9q6iukafr.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtnd',
  );
}
