import 'package:dtnd/l10n/generated/l10n.dart';
import 'package:flutter/material.dart';

mixin OrderMessage {
  String getErrorMessage(BuildContext context, int rc) =>
      _mapMessage[rc] ?? S.of(context).unknown_exception;

  final Map<int, String> _mapMessage = {
    -6004: 'Lệnh đã được xử lý, không được gửi lại.',
    -6007: 'Hủy lệnh không thành công.',
    -6012: 'Tài khoản không đủ sức mua.',
    -6013: 'Không đủ số dư chứng khoán.',
    -6014: 'Lệnh không được hủy.',
    -6015: 'Không được sửa lệnh này.',
    -6016: 'Loại chứng khoán không hợp lệ.',
    -6017: 'Tài Khoản đang chờ kích hoạt.',
    -6019: 'Khối lượng đặt không hợp lệ.',
    -6020: 'Không xác định được thị trường.',
    -6021: 'Giá không phù hợp.',
    -6022: 'Thị trường đóng cửa.',
    -6023: 'Loại lệnh không phù hợp.',
    -6024: 'Không được đặt loại lệnh phiên này.',
    -6025: 'Hệ thống chưa sẵn sàng đặt lệnh ngoài giờ.',
    -6026: 'Không được huỷ/sửa lệnh phiên này.',
    -6027: 'Không được đặt lệnh điều kiện.',
    -6028: 'Tài khoản không được mua - bán.',
    -6029: 'Tài khoản không được ủy quyền.',
    -6030: 'User không có quyền xem tài khoản.',
    -6031: 'Chứng khoán không hợp lệ.',
    -6032: 'Vượt qua tỷ lệ an toàn tài khoản.',
    -6033: 'Chứng khoán đáo hạn không được giao dịch.',
    -6034: 'Vượt qua khối lượng 1000 của phái sinh.',
    -6035: 'Sai giá trần/sàn.',
    -6036: 'Sai bước giá cho trái phiếu.',
    -6037: 'Không được đặt lệnh.',
    -6038: 'Vượt qua tổng vị thế tối đa.',
    -6039: 'Tài khoản mới mở, chưa được giao dịch.',
    -6041: 'Tài khoản hạn chế giao dịch.',
    -6043: 'Không được mua bán cùng phiên.',
    -6045: 'Chứng khoán hết room cho vay',
    -6046: 'Chứng khoán hết room nước ngoài',
    -6047: 'Hết hạn mức mã chứng khoán ',
    -6048: 'Không được sửa đồng thời giá và khối lượng',
    -6666: 'Hết hạn mức nguồn.',
    -6667: 'Hết hạn mức tài khoản.',
    -6668: 'Tài khoản hạn chế bán do QTRR.',
    -6669: 'Lệnh forcesell, KH không được thao tác.',
    -6670: 'Hết hạn mức tổng của nhóm.',
    -6671: 'Hết hạn mức công ty.',
    -8001: 'Không kết nối được với gateway.',
    -8002: 'Thị trường đóng của, không được đặt lệnh.',
    -8003: 'Lệnh không được hủy/sửa.',
    -8004: 'Lệnh đã khớp hết, không được hủy/sửa.',
    -8005: 'Sai mã pin.',
    -8006: 'Không dùng password cũ.',
    -8007: 'Password không hợp lệ.',
    -8008: 'Không có quyền truy cập từ IP ngoài.',
    -8009: 'TRADER HALT.',
    -8010: 'Hệ thống đang thi với HSX, KHÔNG ĐƯỢC ĐẶT LỆNH.',
    -8011: 'BrokerID đang bị chặn MUA.',
    -8012: 'BrokerID đang bị chặn BÁN.',
    -8013: 'BrokerID đang bị chặn giao dịch.',
    -8014: 'BrokerID bị chặn giao dịch thoả thuận.',
    -8015: 'BrokerID bị chặn giao dịch thoả thuận BÁN.',
    -8016: 'BrokerID bị chặn giao dịch thoả thuận MUA.',
    -9998: 'Lệnh chưa được confirm!',
    -9999: 'Không đủ điều kiện sửa.',
    -9001: 'Không được giao dịch mã chứng quyền trên TK margin',
    -8: 'Hệ thống chưa sẵn sàng nhận lệnh'
  };
}

mixin AccountErrorDefinition {
  String getErrorMessage(int rc) =>
      _mapMessage[rc] ?? S.current.unknown_exception;
  final Map<int, String> _mapMessage = {
    2000: "Mã khách hàng không tồn tại",
    2001: "Mã khách hàng đã tồn tại",
    2002: "Khách hàng đã mở TK ",
    2003: "Tài khoản đã tồn tại",
    2004: "Tài khoản không hợp lệ",
    2005: "Ngay mo khong duoc lon hon ngay hien tai ",
    2006: "Số ĐKSH đã tồn tại",
    2007: "Tài khoản không tồn tại/trạng thái tài khoản không hợp lệ",
    2008: "Ngày hiệu lực không hợp lệ",
    2009: "Không được cài 2 khoảng tong tương lai",
    2010: "Gói phí đã hết hiệu lực",
    2011: "Không được xóa các bút toán đã có hiệu lực",
    2012: "Người ủy quyền không hợp lệ",
    2013: "Chủ tk đã ủy quyền cho người khác và khong được quyền thực hiện",
    2014:
        "CMT nguoi yeu cau khong ton tai hoac khong duoc Uy quyen hoac Uy quyen da het han!",
    2015: "Tai khoan ATS, ban khong the thuc hien.",
    2016: "Ngay het han phai lon hon ngay hien tai",
    2017: "Ngày cấp phải nhỏ hơn ngày hiện tại",
    2018: "Số điện thoại không hợp lệ",
    2019: "Email không hợp lệ",
    2020: "Nơi cấp không hợp lệ",
    2021: "Mã số thuế không hợp lệ",
    2022: "Địa chỉ liên hệ không hợp lệ",
    2023: "Người đại diện không hợp lệ",
    2024: "Ngày cấp người ủy quyền phải nhỏ hơn ngày hiện tại",
    2025: "Chức vụ không được để trống",
    2026: "Điện thoại cố định không được để trống",
    2027: "Điện thoại di động không được để trống",
    2028: "Đia chỉ thường trú không hợp lệ",
    2029: "Khách hàng chưa đủ tuổi",
    2030: "Tên người giám hộ không hợp lệ",
    2031: "Quan hệ với chủ tài khoản không hợp lệ",
    2032: "Số giấy tờ người giám hộ không hợp lệ",
    2033: "Ngày cấp người giám hộ không hợp lệ",
    2034: "Nơi cấp người giám hộ không hợp lệ",
    2035: "địa chỉ người giám hộ không hợp lệ",
    2036: "Số điện thoại người giám hộ không hợp lệ",
    2037: "Email người giám hộ không hợp lệ",
    2038: "Không được mở tài khoản",
    2039: "Đã có khách hàng đăng ký số điện thoại này này",
    2040: "Đã có khách hàng đăng ký email này",
    2041: "Số điện thoại và email này đã đăng ký trên hệ thống",
    2042: "Gói phí này đã gắn cho khách hàng",
    2043: "Thông tin không hợp lệ",
    2044: "Tài khoản đã phát sinh giao dịch tiền",
    2045: "Tài khoản đã phát sinh giao dịch CK",
  };
}
