import 'package:dtnd/=models=/response/order_model/i_order_model.dart';
import 'package:dtnd/generated/l10n.dart';
import 'package:flutter/material.dart';

class NewOrderMessage {
  static String getErrorMessage(BuildContext context, int rc) =>
      _mapMessage[rc] ?? S.of(context).unknown_exception;

  static final Map<int, String> _mapMessage = {
    -6004: 'Lệnh đã được xử lý, không được gửi lại.',
    -6007: 'Hủy lệnh không thành công.',
    -6012: 'Tài khoản không đủ sức mua.',
    -6013: 'Không đủ số dư chứng khoán.',
    -6014: 'Lệnh không được hủy.',
    -6015: 'Không được sửa lệnh này.',
    -6016: 'Loại chứng khoán không hợp lệ.',
    -6017: 'Tài Khoản đang chờ kích hoạt.',
    -6019: 'Khối lượng đặt không hợp lệ.',
    -6020: 'Không xác định được thị trường.',
    -6021: 'Giá không phù hợp.',
    -6022: 'Thị trường đóng cửa.',
    -6023: 'Loại lệnh không phù hợp.',
    -6024: 'Không được đặt loại lệnh phiên này.',
    -6025: 'Hệ thống chưa sẵn sàng đặt lệnh ngoài giờ.',
    -6026: 'Không được huỷ/sửa lệnh phiên này.',
    -6027: 'Không được đặt lệnh điều kiện.',
    -6028: 'Tài khoản không được mua - bán.',
    -6029: 'Tài khoản không được ủy quyền.',
    -6030: 'User không có quyền xem tài khoản.',
    -6031: 'Chứng khoán không hợp lệ.',
    -6032: 'Vượt qua tỷ lệ an toàn tài khoản.',
    -6033: 'Chứng khoán đáo hạn không được giao dịch.',
    -6034: 'Vượt qua khối lượng 1000 của phái sinh.',
    -6035: 'Sai giá trần/sàn.',
    -6036: 'Sai bước giá cho trái phiếu.',
    -6037: 'Không được đặt lệnh.',
    -6038: 'Vượt qua tổng vị thế tối đa.',
    -6039: 'Tài khoản mới mở, chưa được giao dịch.',
    -6041: 'Tài khoản hạn chế giao dịch.',
    -6043: 'Không được mua bán cùng phiên.',
    -6045: 'Chứng khoán hết room cho vay',
    -6046: 'Chứng khoán hết room nước ngoài',
    -6047: 'Hết hạn mức mã chứng khoán ',
    -6048: 'Không được sửa đồng thời giá và khối lượng',
    -6666: 'Hết hạn mức nguồn.',
    -6667: 'Hết hạn mức tài khoản.',
    -6668: 'Tài khoản hạn chế bán do QTRR.',
    -6669: 'Lệnh forcesell, KH không được thao tác.',
    -6670: 'Hết hạn mức tổng của nhóm.',
    -6671: 'Hết hạn mức công ty.',
    -8001: 'Không kết nối được với gateway.',
    -8002: 'Thị trường đóng của, không được đặt lệnh.',
    -8003: 'Lệnh không được hủy/sửa.',
    -8004: 'Lệnh đã khớp hết, không được hủy/sửa.',
    -8005: 'Sai mã pin.',
    -8006: 'Không dùng password cũ.',
    -8007: 'Password không hợp lệ.',
    -8008: 'Không có quyền truy cập từ IP ngoài.',
    -8009: 'TRADER HALT.',
    -8010: 'Hệ thống đang thi với HSX, KHÔNG ĐƯỢC ĐẶT LỆNH.',
    -8011: 'BrokerID đang bị chặn MUA.',
    -8012: 'BrokerID đang bị chặn BÁN.',
    -8013: 'BrokerID đang bị chặn giao dịch.',
    -8014: 'BrokerID bị chặn giao dịch thoả thuận.',
    -8015: 'BrokerID bị chặn giao dịch thoả thuận BÁN.',
    -8016: 'BrokerID bị chặn giao dịch thoả thuận MUA.',
    -9998: 'Lệnh chưa được confirm!',
    -9999: 'Không đủ điều kiện sửa.',
    -9001: 'Không được giao dịch mã chứng quyền trên TK margin',
    -8: 'Hệ thống chưa sẵn sàng nhận lệnh'
  };
}
